"""ai schema foundation

Six empty tables and their indexes. Delivered by C05.

Hand-written rather than autogenerated: `autogenerate` cannot express HNSW
operator classes, GIN over arrays, or generated columns, so the whole revision
would have to be rewritten anyway — and a model-vs-migration drift test would
report noise forever, because the comparison does not look inside indexes.

Three choices in here are load-bearing and none of them is cosmetic:

* **HNSW with `vector_cosine_ops`.** An index whose operator class disagrees
  with the query operator is silently never used — no error, no warning, just a
  sequential scan. On ~1,500 vectors that is invisible even in latency, which is
  why `test_hnsw_index_uses_cosine_operator_class` asserts it against the
  catalog.
* **Closed vocabularies as CHECK constraints, never as enumerated types.** A
  database type created for a column survives dropping its table, so a revert
  would leave it orphaned and the next upgrade would fail with "type already
  exists" — weeks later, with nothing pointing at the cause.
* **No foreign keys into `public`.** Product, point-of-sale and family ids are
  plain uuids. A real constraint would couple this schema to the lifecycle of
  EF Core's tables and would contradict the ownership boundary.

Revision ID: f46c55c056e2
Revises:
Create Date: 2026-08-15
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "f46c55c056e2"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

AI = "ai"

# Dimension of text-embedding-3-small, fixed on purpose: changing it would mean
# re-embedding the whole corpus, and the design says a model change lands in a
# NEW column rather than overwriting this one.
EMBEDDING_DIM = 1536

# Build-time HNSW parameters, declared rather than inherited. pgvector defaults
# `ef_construction` to 64; 128 is the value the S8 material fixes for 1536
# dimensions. `ef_search` is a query-time knob and belongs to C14, not here.
HNSW = {"m": 16, "ef_construction": 128}

TEXT_ARRAY_DEFAULT = sa.text("'{}'::text[]")


def _text_array(name: str) -> sa.Column:
    """A never-null tag array: absence is an empty array, never a NULL."""
    return sa.Column(
        name,
        postgresql.ARRAY(sa.Text()),
        nullable=False,
        server_default=TEXT_ARRAY_DEFAULT,
    )


def _spanish_tsvector(source: str) -> sa.Column:
    """A full-text column the database computes, so no write path can skip it.

    The two-argument form of `to_tsvector` is IMMUTABLE and therefore legal in a
    generated column; the one-argument form is not, because it depends on the
    session's `default_text_search_config` — which is exactly the mechanism by
    which the language could drift without anyone noticing.
    """
    return sa.Column(
        "tsv",
        postgresql.TSVECTOR(),
        sa.Computed(f"to_tsvector('spanish', {source})", persisted=True),
    )


def upgrade() -> None:
    # Normally a no-op: `env.py` provisioned both before Alembic materialised
    # its version table. Declared here anyway so the revision's SQL stays
    # self-describing.
    #
    # Guarded with an explicit check rather than `IF NOT EXISTS`, because
    # PostgreSQL evaluates the privilege *before* the short-circuit: on RDS,
    # where the administrator provisions and the service role only migrates,
    # `CREATE SCHEMA IF NOT EXISTS` fails with "permission denied" even though
    # the schema is already there.
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = '{AI}') THEN
                CREATE SCHEMA "{AI}";
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'vector') THEN
                CREATE EXTENSION vector;
            END IF;
        END
        $$
        """
    )

    _create_product_document()
    _create_knowledge()
    _create_pos_projection()
    _create_co_occurrence()
    _create_sync_failure()


def downgrade() -> None:
    """Drop the six tables and nothing else.

    Schema `ai` stays because it holds Alembic's own version table — dropping it
    would remove the row this very operation is about to write. The extension
    stays because it is shared database-wide and another consumer may rely on
    it. Since no enumerated types were created, nothing is left orphaned, which
    is what makes re-applying the revision work.
    """
    op.drop_table("sync_failure", schema=AI)
    op.drop_table("co_occurrence", schema=AI)
    op.drop_table("pos_projection", schema=AI)
    op.drop_table("knowledge_chunk", schema=AI)
    op.drop_table("knowledge_document", schema=AI)
    op.drop_table("product_document", schema=AI)


def _create_product_document() -> None:
    """One row per product, no chunking (design §7.2)."""
    op.create_table(
        "product_document",
        # Assigned by the .NET API. No foreign key: see the module docstring.
        sa.Column("product_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("collection_name", sa.Text()),
        # A copy for banding and ordering. The authoritative figure is .NET's.
        sa.Column("price", sa.Numeric(10, 2)),
        sa.Column("price_band", sa.Text()),
        sa.Column("piece_type", sa.Text()),
        sa.Column("stone_type", sa.Text()),
        sa.Column("size_label", sa.Text()),
        # A list, not a scalar: the filter is overlap (&&) and containment (@>),
        # so "something in silver" also matches a piece that is silver *and*
        # gold-plated (design §7.3).
        _text_array("materials"),
        sa.Column("family_id", postgresql.UUID(as_uuid=True)),
        sa.Column("family_name", sa.Text()),
        sa.Column("variant_label", sa.Text()),
        _text_array("color_tags"),
        _text_array("style_tags"),
        _text_array("occasion_tags"),
        # Canonical SourceText, built by C11 in a fixed order.
        sa.Column("doc_text", sa.Text(), nullable=False),
        sa.Column("source_hash", sa.CHAR(64), nullable=False),
        # Nullable on purpose: a document may be upserted before its embedding
        # has been computed, which is what lets C13 separate the two steps.
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        _spanish_tsvector("doc_text"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("data_origin", sa.Text(), nullable=False),
        sa.Column("embedding_model", sa.Text()),
        sa.Column("embedding_version", sa.Text()),
        sa.Column("indexed_at", sa.TIMESTAMP(timezone=True)),
        # Every metric is reported broken down by this column (design §8.1.1),
        # so an unexpected value has to be impossible rather than unlikely.
        sa.CheckConstraint(
            "data_origin IN ('real', 'synthetic')",
            name="ck_product_document_data_origin",
        ),
        # Permissive on purpose: C09 fixes the band vocabulary when it computes
        # them. Until then this rejects only the empty string, which is the one
        # value that is certainly a defect.
        sa.CheckConstraint(
            "price_band IS NULL OR length(btrim(price_band)) > 0",
            name="ck_product_document_price_band",
        ),
        schema=AI,
    )

    # Aligned with the `<=>` operator C14 will query with. Misaligning this
    # disables the index without raising anything.
    op.create_index(
        "ix_product_document_embedding_hnsw",
        "product_document",
        ["embedding"],
        schema=AI,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with=HNSW,
    )
    op.create_index(
        "ix_product_document_tsv",
        "product_document",
        ["tsv"],
        schema=AI,
        postgresql_using="gin",
    )
    # Without this, every material filter degrades to a sequential scan.
    op.create_index(
        "ix_product_document_materials",
        "product_document",
        ["materials"],
        schema=AI,
        postgresql_using="gin",
    )

    # Structural filters (§7.2) and the reporting dimension of §8.1.1. At ~1,500
    # rows none of these improves a measurable latency; they are here because
    # adding them later costs a migration and having them costs nothing.
    for column in ("family_id", "piece_type", "price_band", "data_origin"):
        op.create_index(
            f"ix_product_document_{column}",
            "product_document",
            [column],
            schema=AI,
        )


def _create_knowledge() -> None:
    """General commercial knowledge — never scoped to a product."""
    op.create_table(
        "knowledge_document",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("doc_type", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.Text()),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "doc_type IN ('material', 'talla', 'guion_venta', 'politica', 'faq')",
            name="ck_knowledge_document_doc_type",
        ),
        schema=AI,
    )
    op.create_index(
        "ix_knowledge_document_doc_type",
        "knowledge_document",
        ["doc_type"],
        schema=AI,
    )

    op.create_table(
        "knowledge_chunk",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        # Intra-schema foreign key, unlike the ids that point at `public`.
        # Deleting a document must take its chunks with it, with no application
        # logic involved.
        sa.Column(
            "document_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey(f"{AI}.knowledge_document.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.Column("embedding", Vector(EMBEDDING_DIM)),
        _spanish_tsvector("content"),
        sa.Column("embedding_model", sa.Text()),
        sa.Column("embedding_version", sa.Text()),
        sa.Column("indexed_at", sa.TIMESTAMP(timezone=True)),
        # A chunking invariant, and it also serves lookups by document.
        sa.UniqueConstraint(
            "document_id",
            "chunk_index",
            name="uq_knowledge_chunk_document_chunk_index",
        ),
        schema=AI,
    )
    op.create_index(
        "ix_knowledge_chunk_embedding_hnsw",
        "knowledge_chunk",
        ["embedding"],
        schema=AI,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with=HNSW,
    )
    op.create_index(
        "ix_knowledge_chunk_tsv",
        "knowledge_chunk",
        ["tsv"],
        schema=AI,
        postgresql_using="gin",
    )
    # Structured filters over chunk metadata would otherwise scan the table.
    op.create_index(
        "ix_knowledge_chunk_metadata",
        "knowledge_chunk",
        ["metadata"],
        schema=AI,
        postgresql_using="gin",
    )


def _create_pos_projection() -> None:
    """Ranking prior, never an excluding filter (design §7.6)."""
    op.create_table(
        "pos_projection",
        sa.Column("pos_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("product_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("is_assigned_hint", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        # A bucket, never the exact quantity. The projection can be stale, and
        # storing the real number would invite showing it; as a bucket it can
        # only be used as a ranking signal. The quantity is .NET's to state.
        sa.Column("qty_bucket", sa.Text(), nullable=False),
        sa.Column("sales_30d", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("sales_90d", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_sale_at", sa.TIMESTAMP(timezone=True)),
        # Lets the response report `projection_age_seconds` (C22).
        sa.Column(
            "refreshed_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.CheckConstraint(
            "qty_bucket IN ('0', '1-2', '3+')",
            name="ck_pos_projection_qty_bucket",
        ),
        schema=AI,
    )
    # Reverse lookup: which points of sale hold this product.
    op.create_index(
        "ix_pos_projection_product_id",
        "pos_projection",
        ["product_id"],
        schema=AI,
    )


def _create_co_occurrence() -> None:
    """Complementary-recommendation signal, one row per unordered pair."""
    op.create_table(
        "co_occurrence",
        sa.Column("product_a", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("product_b", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("co_sales_count", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("last_seen_at", sa.TIMESTAMP(timezone=True)),
        # Without this the same pair can be stored in both orientations and C27
        # counts every co-sale twice.
        sa.CheckConstraint("product_a < product_b", name="ck_co_occurrence_orientation"),
        schema=AI,
    )


def _create_sync_failure() -> None:
    """A failed batch must not block the others, and must not be lost."""
    op.create_table(
        "sync_failure",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("feed", sa.Text(), nullable=False),
        sa.Column("cursor_since", sa.TIMESTAMP(timezone=True)),
        sa.Column("payload", postgresql.JSONB()),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column("next_retry_at", sa.TIMESTAMP(timezone=True)),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        schema=AI,
    )
    # The retry queue is read by due date; without this it is a table scan.
    op.create_index(
        "ix_sync_failure_next_retry_at",
        "sync_failure",
        ["next_retry_at"],
        schema=AI,
    )
